blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://ui.soundsdesigned.com
    about: Check the documentation for guides and examples.
  - name: ğŸ“š Discord
    url: https://go.soundsdesigned.com/discord
    about: Consider asking questions in the help channel.
